[project]
name = "dbd-build-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "denisinside", email = "d.shvachka@ukma.edu.ua" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4==4.14.3",
    "chromadb==1.5.5",
    "fastapi>=0.141.1",
    "langchain-openrouter>=0.2.7",
    "langchain-tavily>=0.2.18",
    "openai==1.82.0",
    "pymongo==4.13.2",
    "python-dotenv==1.1.0",
    "requests==2.32.5",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
dbd-build-generator = "dbd_build_generator:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
