/**
 * Rotating placeholder content for the build prompt textarea (frontend/app/page.tsx).
 * Plain example requests, not real perk/entity names the model has to honor —
 * grounding happens server-side regardless of what's typed here.
 */
export const EXAMPLE_PROMPTS: string[] = [
  "Survivor build for fast generator repairs and safe escapes.",
  "Killer build for The Huntress focused on long-range hatchet pressure.",
  "Stealthy Survivor build for someone who hates chases.",
  "Aggressive Killer build that snowballs after the first down.",
  "Survivor build for solo queue with lots of information.",
  "Killer build for The Nurse focused on chase efficiency.",
  "Beginner-friendly Survivor build with simple, forgiving perks.",
  "Killer build that punishes generator rushing.",
  "Survivor build built around looping and pallet efficiency.",
  "Killer build for The Trapper with heavy area denial.",
  "Survivor healer build for altruistic team play.",
  "Killer build for The Wraith focused on stealth and ambush.",
  "Survivor build for escaping through the hatch late game.",
  "Killer build that slows the game down with generator regression.",
  "Survivor build for a toolbox-focused generator rusher.",
  "Killer build for The Spirit with strong mind games.",
  "Survivor build for someone who always gets tunneled.",
  "Killer build for The Doctor focused on tracking Survivors.",
  "Survivor build for boldly unhooking teammates safely.",
  "Killer build for The Hag with trap-based map control.",
  "Survivor build using a medkit for constant self-healing.",
  "Killer build for The Plague focused on area corruption.",
  "Survivor build for reading auras and predicting the Killer.",
  "Killer build for The Legion focused on chain-hitting Survivors.",
  "Survivor build for a flashlight save specialist.",
  "Killer build for The Executioner with cage of atonement pressure.",
  "Survivor build focused on totem cleansing and hex counters.",
  "Killer build for The Artist with strong map-wide pressure.",
  "Survivor build for a first-time player who wants to learn the basics.",
  "Killer build for The Blight focused on rapid chase mobility.",
  "Survivor build for looping around structures near shack.",
  "Killer build for The Twins with double-threat pressure.",
  "Survivor build for a stealthy key-and-hatch escape strategy.",
  "Killer build for The Oni focused on demon dash chases.",
  "Survivor build that keeps the team's morale up after early downs.",
  "Killer build for The Deathslinger with ranged chain pressure.",
  "Survivor build for gen-rushing a slow, camping Killer.",
  "Killer build for The Pig focused on reverse bear trap pressure.",
  "Survivor build for a chase-focused main-event distraction.",
  "Killer build for The Clown with gas-based zoning.",
  "Survivor build for someone who wants to counter tunneling.",
  "Killer build for The Freddy Krueger with dream world pressure.",
  "Survivor build for map awareness and rotational efficiency.",
  "Killer build for The Ghost Face with stealth stalking.",
  "Survivor build that maximizes healing speed for the whole team.",
  "Killer build for The Demogorgon with portal map control.",
  "Survivor build for a competitive SWF team comp.",
  "Killer build for The Cenobite with chain hunt pressure.",
  "Survivor build for escaping without ever touching a generator.",
  "Killer build for The Cannibal focused on basement plays.",
  "Survivor build for surviving against a slugging Killer.",
  "Killer build for The Nemesis with zombie-assisted pressure.",
  "Survivor build for a stealth-only build with no loud perks.",
  "Killer build for The Onryo with condemned stacking pressure.",
  "Survivor build for endgame collapse escapes.",
  "Killer build for The Dredge focused on locker teleport ambush.",
  "Survivor build for repairing generators as fast as possible alone.",
  "Killer build for The Skull Merchant with drone-based tracking.",
  "Survivor build focused on protecting the obsession.",
  "Killer build for The Singularity with biopod-based tracking.",
  "Survivor build for map-specific chase counters near strong loops.",
  "Killer build for The Xenomorph with tunnel-based ambush.",
  "Survivor build for a flashbang and blind-heavy playstyle.",
  "Killer build for The Good Guy with small hitbox stealth.",
  "Survivor build for someone who plays a lot of second chase.",
  "Killer build for The Unknown with illusion-based mind games.",
  "Survivor build for baiting hits away from injured teammates.",
  "Killer build for The Vecna with spell-based zoning.",
  "Survivor build for a fun, meme-y challenge run.",
  "Killer build for The Houndmaster with dog-assisted tracking.",
  "Survivor build for a build focused entirely on boldness points.",
  "Killer build that discourages Survivors from looping at all.",
  "Survivor build for a new player who keeps dying first.",
  "Killer build for a 3-gen strategy on small maps.",
  "Survivor build for someone playing against a Mori-heavy Killer.",
  "Killer build focused on info gathering rather than chase power.",
  "Survivor build for a high-mobility item like a map or compass.",
  "Killer build for punishing Survivors who body-block for each other.",
  "Survivor build for team utility with minimal selfish perks.",
  "Killer build for zoning Survivors away from the exit gates.",
  "Survivor build for someone who wants to counter slugging for the 4k.",
  "Killer build with strong early-game pressure before gens pop.",
  "Survivor build for maximizing skill check bonuses.",
  "Killer build for a stealth-heavy ambush playstyle on any Killer.",
  "Survivor build for a completionist who wants every counter covered.",
  "Killer build for someone who wants to patrol generators efficiently.",
  "Survivor build for escaping solo without any teammates left.",
  "Killer build focused on hex totem synergy and protection.",
  "Survivor build for reading the Killer's terror radius and heartbeat.",
  "Killer build for chaining hits across multiple Survivors quickly.",
  "Survivor build for someone who wants to farm points, not necessarily win.",
  "Killer build for an anti-loop playstyle on structures with strong pallets.",
  "Survivor build for rescuing from the basement safely.",
  "Killer build for tracking scratch marks and blood trails effectively.",
  "Survivor build for someone who wants to juke every mind game.",
  "Killer build for punishing greedy generator repairs.",
  "Survivor build for map control using windows and vaults.",
  "Killer build for a build that scales well into the late game.",
  "Survivor build for a duo queue with a coordinated partner.",
  "Killer build for someone who struggles with chase mechanics.",
  "Survivor build for countering a Killer who tunnels the obsession.",
  "Killer build for pressuring generators without leaving chase.",
  "Survivor build for a stealth build around lockers and hiding spots.",
  "Killer build for a build that discourages flashlight saves.",
  "Survivor build for the strongest possible chase perks combination.",
  "Killer build for someone who wants consistent, low-variance games.",
]
