import type { LucideIcon } from "lucide-react"
import {
  BookOpen,
  Trophy,
  Eye,
  Wrench,
  Zap,
  Gauge,
  Footprints,
  Cog,
  Target,
  Users,
  ShieldAlert,
  Timer,
  Sparkles,
  HeartPulse,
  Radar,
  Ghost,
  Skull,
  Flame,
  Swords,
  Wind,
  Crosshair,
  Brain,
  Map,
  Compass,
  DoorOpen,
  Key,
  Flashlight,
  Bandage,
  ShieldCheck,
  ShieldOff,
  Hourglass,
  Handshake,
  HelpCircle,
} from "lucide-react"

// Maps string keys stored in build data to concrete icon components.
// This keeps the data layer free of React/component imports so a build
// can be described entirely with plain strings.
const registry: Record<string, LucideIcon> = {
  book: BookOpen,
  trophy: Trophy,
  eye: Eye,
  wrench: Wrench,
  zap: Zap,
  gauge: Gauge,
  footprints: Footprints,
  cog: Cog,
  target: Target,
  users: Users,
  "shield-alert": ShieldAlert,
  timer: Timer,
  sparkles: Sparkles,
  heart: HeartPulse,
  radar: Radar,
  ghost: Ghost,
  skull: Skull,
  flame: Flame,
  swords: Swords,
  wind: Wind,
  crosshair: Crosshair,
  brain: Brain,
  map: Map,
  compass: Compass,
  "door-open": DoorOpen,
  key: Key,
  flashlight: Flashlight,
  bandage: Bandage,
  "shield-check": ShieldCheck,
  "shield-off": ShieldOff,
  hourglass: Hourglass,
  handshake: Handshake,
}

export function getIcon(name: string): LucideIcon {
  return registry[name] ?? HelpCircle
}
